### ISSUE TITLE
Project issue task 2

### ISSUE THREAD

**Issue by arghyakusumdas** [arghyakusumdas/ThanosCar#4]
1) Add a subtask called 'Wait on hardware arrival' for the task  'procure hardware'. Add some elapsed time for this. Elapsed time should not jeopardize the current schedule.
2) what is dc? Use some meaningful name

**Comment by jonejo** [comment]
Issue has been resolved. I could not find DC in any of the project. I utilized the ctrl-f function to search for it and could not find anything, I even checked in the notes i made. I also added a predecessor to the task after procure hardware in order to make it more realistic because we can't start networking until we have all the hardware situated 

-John
